### ISSUE TITLE
Error: watch api/models ENOSPC after sails lift command

### ISSUE THREAD

**Issue by kapit4n** [kapit4n/mockupero-api#29]
log:
(node:3723) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

info: Starting app...

(node:3723) DeprecationWarning: sys is deprecated. Use util instead.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch api/models ENOSPC
  at exports._errnoException (util.js:1036:11)
  at FSWatcher.start (fs.js:1429:19)
  at Object.fs.watch (fs.js:1456:11)
  at createFsWatchInstance (/home/llll/projects/mockupero-api/node_modules/chokidar/lib/nodefs-handler.js:37:15)
  at setFsWatchListener (/home/llll/projects/mockupero-api/node_modules/chokidar/lib/nodefs-handler.js:80:15)
  at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/llll/projects/mockupero-api/node_modules/chokidar/lib/nodefs-handler.js:228:14)
  at FSWatcher.NodeFsHandler._handleDir (/home/llll/projects/mockupero-api/node_modules/chokidar/lib/nodefs-handler.js:407:19)
  at FSWatcher.<anonymous> (/home/llll/projects/mockupero-api/node_modules/chokidar/lib/nodefs-handler.js:455:19)
  at FSWatcher.<anonymous> (/home/llll/projects/mockupero-api/node_modules/chokidar/lib/nodefs-handler.js:460:16)
  at FSReqWrap.oncomplete (fs.js:123:15)

**Solution:**
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

**Comment by kapit4n** [comment]
https://github.com/gruntjs/grunt-contrib-watch/issues/236
